const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path'); const sqlite3 = require('sqlite3').verbose();
const { runAsync, getAsync } = require('../utils/sqliteAsync');
const manual = require('../services/assistente/actions/manualPaymentCommand');
const { createActionGateway, createMemoryAuditStore } = require('../services/assistente/actions/actionGateway');
const { createActionRegistry } = require('../services/assistente/actions/actionRegistry');

async function fixture() { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'assistente-manual-')); const db = new sqlite3.Database(path.join(dir, 'fixture.db'));
  await runAsync(db, 'CREATE TABLE clientes (id INTEGER PRIMARY KEY, nome TEXT, cpf TEXT)'); await runAsync(db, 'CREATE TABLE emprestimos (id INTEGER PRIMARY KEY, cliente_id INTEGER, modalidade TEXT, versao_atual INTEGER, capital_restante REAL)');
  await runAsync(db, 'CREATE TABLE parcelas (id INTEGER PRIMARY KEY, emprestimo_id INTEGER, numero INTEGER, valor_total REAL, valor_capital REAL, valor_juros REAL, juros_pendentes REAL, juros_adicionais REAL, valor_pago REAL, pago INTEGER, data_pagamento TEXT, versao INTEGER)'); await runAsync(db, 'CREATE TABLE pagamentos (id INTEGER PRIMARY KEY AUTOINCREMENT, emprestimo_id INTEGER, valor REAL, data TEXT, tipo_pagamento TEXT, observacao TEXT, parcela_origem INTEGER)'); await runAsync(db, 'CREATE TABLE caixa_movimentos (id INTEGER PRIMARY KEY, valor_total REAL, valor_juros REAL, valor_capital REAL)');
  await runAsync(db, "INSERT INTO clientes VALUES (1,'Cliente Manual','000.000.000-00')"); await runAsync(db, "INSERT INTO emprestimos VALUES (10,1,'parcelado',1,100)"); await runAsync(db, 'INSERT INTO parcelas VALUES (100,10,1,117,100,10,5,2,0,0,NULL,1)');
  const command = { normalizeIntent: manual.normalizeIntent, createPaymentPreview: (i) => manual.createPaymentPreview(i, { dbHandle: db }), executePayment: (a, f) => manual.executePayment(a, f, { dbHandle: db, registrarEntradaPagamento: async (p) => runAsync(db, 'INSERT INTO caixa_movimentos VALUES (1,?,?,?)', [p.valor_total, p.valor_juros, p.valor_capital]) }) }; return { db, command, async close() { await new Promise((r) => db.close(r)); fs.rmSync(dir, { recursive: true, force: true }); } }; }
function intent(overrides = {}) { return { action: 'registrar_pagamento_manual', cliente_id: 1, emprestimo_id: 10, valor: 50, data: '2026-08-19', abatimentos: [{ parcela_id: 100, valor: 50 }], ...overrides }; }
test('manual registrado segue a regra oficial, preview nao persiste e caixa recebe split', async () => { const f = await fixture(); try { const audit = createMemoryAuditStore(); const gateway = createActionGateway({ actionRegistry: createActionRegistry({ manualCommand: f.command }), auditStore: audit }); const p = await gateway.createPreview({ sessionId: 's', intent: intent() });
  assert.deepEqual(p.preview.impacto.distribuicao, { juros_adicionais: 2, juros_pendentes: 5, juros_base: 10, capital: 33 }); assert.equal((await getAsync(f.db, 'SELECT COUNT(*) total FROM pagamentos')).total, 0);
  await gateway.confirm({ sessionId: 's', confirmationToken: p.confirmation_token }); const parcela = await getAsync(f.db, 'SELECT valor_capital,valor_juros,juros_pendentes,juros_adicionais,valor_pago FROM parcelas'); assert.deepEqual({ ...parcela }, { valor_capital: 67, valor_juros: 0, juros_pendentes: 0, juros_adicionais: 0, valor_pago: 50 }); const caixa = await getAsync(f.db, 'SELECT * FROM caixa_movimentos'); assert.deepEqual({ ...caixa }, { id: 1, valor_total: 50, valor_juros: 17, valor_capital: 33 }); assert.doesNotMatch(JSON.stringify(audit.entries), /Cliente Manual|000\.000/);
} finally { await f.close(); } });
test('manual rejeita contrato invalido, estado alterado e rollback de caixa', async () => { const f = await fixture(); try { const registry = createActionRegistry({ manualCommand: f.command }); const gateway = createActionGateway({ actionRegistry: registry, auditStore: createMemoryAuditStore() }); await assert.rejects(() => gateway.createPreview({ sessionId: 's', intent: intent({ abatimentos: [{ parcela_id: 100, valor: 60 }] }) }), { code: 'invalid_allocations' }); await assert.rejects(() => gateway.createPreview({ sessionId: 's', intent: { ...intent(), extra: true } }), { code: 'invalid_action_contract' }); const p = await gateway.createPreview({ sessionId: 's', intent: intent() }); await runAsync(f.db, 'UPDATE parcelas SET valor_juros=9 WHERE id=100'); await assert.rejects(() => gateway.confirm({ sessionId: 's', confirmationToken: p.confirmation_token }), { code: 'state_changed' }); assert.equal((await getAsync(f.db, 'SELECT COUNT(*) total FROM pagamentos')).total, 0);
  const failing = { ...f.command, executePayment: (a, fp) => manual.executePayment(a, fp, { dbHandle: f.db, registrarEntradaPagamento: async () => { throw new Error('caixa'); } }) }; const failingGateway = createActionGateway({ actionRegistry: createActionRegistry({ manualCommand: failing }), auditStore: createMemoryAuditStore() }); const retry = await failingGateway.createPreview({ sessionId: 'x', intent: { ...intent(), valor: 49, abatimentos: [{ parcela_id: 100, valor: 49 }] } }); await assert.rejects(() => failingGateway.confirm({ sessionId: 'x', confirmationToken: retry.confirmation_token })); assert.equal((await getAsync(f.db, 'SELECT COUNT(*) total FROM pagamentos')).total, 0);
} finally { await f.close(); } });
