const crypto = require('crypto');
const aplicarDescontoProxima = require('../../../utils/desconto_proxima');
const { runAsync, getAsync, allAsync } = require('../../../utils/sqliteAsync');
const { splitNormalPaymentFromParcela } = require('../../pagamentos/paymentSplit');
const { claimActionExecution } = require('./actionIdempotency');
function money(value) { const n = Number(value); return Number.isFinite(n) ? Number(n.toFixed(2)) : null; }
function positiveId(value) { const n = Number(value); return Number.isInteger(n) && n > 0 ? n : null; }
function isoDate(value) { const s = String(value || '').trim(); const d = new Date(`${s}T00:00:00Z`); return /^\d{4}-\d{2}-\d{2}$/.test(s) && !Number.isNaN(d.getTime()) && d.toISOString().slice(0, 10) === s ? s : null; }
function error(code, message) { const e = new Error(message); e.code = code; return e; }
function defaultDb() { return require('../../../models/database'); }
function defaultRegistrarEntradaPagamento() { return require('../../caixaService').registrarEntradaPagamento; }
function normalizeIntent(intent = {}) { if (!intent || typeof intent !== 'object' || Array.isArray(intent)) throw error('invalid_action', 'Intencao de acao invalida.'); const allowed = new Set(['action', 'cliente_id', 'emprestimo_id', 'valor', 'data']); if (Object.keys(intent).some((key) => !allowed.has(key))) throw error('invalid_action_contract', 'A intencao contem campos nao permitidos.'); if (String(intent.action || '') !== 'desconto_proxima') throw error('unsupported_action', 'Acao nao suportada.'); const out = { action: 'desconto_proxima', cliente_id: positiveId(intent.cliente_id), emprestimo_id: positiveId(intent.emprestimo_id), valor: money(intent.valor), data: isoDate(intent.data) }; if (!out.cliente_id || !out.emprestimo_id) throw error('entity_required', 'Cliente e emprestimo devem ser informados por ID exato.'); if (out.valor == null || out.valor <= 0) throw error('invalid_amount', 'O valor do pagamento deve ser positivo.'); if (!out.data) throw error('invalid_date', 'A data deve estar no formato YYYY-MM-DD.'); return out; }
async function loadState(normalized, dbHandle) { const cliente = await getAsync(dbHandle, 'SELECT id,nome FROM clientes WHERE id=?', [normalized.cliente_id]); if (!cliente) throw error('client_not_found', 'Cliente nao encontrado.'); const emprestimo = await getAsync(dbHandle, 'SELECT id,cliente_id,modalidade,versao_atual,capital_restante FROM emprestimos WHERE id=?', [normalized.emprestimo_id]); if (!emprestimo) throw error('loan_not_found', 'Emprestimo nao encontrado.'); if (Number(emprestimo.cliente_id) !== normalized.cliente_id) throw error('loan_client_mismatch', 'O emprestimo nao pertence ao cliente informado.'); if (String(emprestimo.modalidade || '').toLowerCase() !== 'parcelado') throw error('unsupported_loan_type', 'A acao exige emprestimo parcelado.'); const parcelas = await allAsync(dbHandle, `SELECT p.* FROM parcelas p JOIN emprestimos e ON e.id=p.emprestimo_id WHERE p.emprestimo_id=? AND (p.versao IS NULL OR p.versao=e.versao_atual) ORDER BY p.numero,p.id`, [normalized.emprestimo_id]); const atualIndex = parcelas.findIndex((p) => !Number(p.pago || 0)); if (atualIndex < 0) throw error('loan_closed', 'O emprestimo nao possui parcela em aberto.'); return { cliente, emprestimo, parcelas, atualIndex, atual: parcelas[atualIndex] }; }
function fingerprint(state, args) { return crypto.createHash('sha256').update(JSON.stringify({ emprestimo: [state.emprestimo.id, state.emprestimo.versao_atual, money(state.emprestimo.capital_restante)], parcelas: state.parcelas.map((p) => [p.id,p.numero,p.valor_total,p.valor_capital,p.valor_juros,p.juros_pendentes,p.juros_adicionais,p.valor_pago,p.valor_excedente,p.pago,p.vencimento,p.versao]), arguments: args })).digest('hex'); }
function buildPreview(state, normalized, updates) { const updateMap = new Map(updates.map((p) => [Number(p.id), p])); const atualAfter = updateMap.get(Number(state.atual.id)); const futures = updates.slice(1).map((update) => { const before = state.parcelas.find((p) => Number(p.id) === Number(update.id)); return { id: Number(update.id), numero: Number(before.numero), valor_anterior: money(before.valor_total), valor_posterior: money(update.valor_total), desconto: money(Number(before.valor_total || 0) - Number(update.valor_total || 0)), vencimento: before.vencimento || null }; }); const excedente = money(atualAfter.valor_excedente || 0); const preview = { cliente: { id: Number(state.cliente.id), nome: String(state.cliente.nome || '') }, emprestimo: { id: Number(state.emprestimo.id) }, pagamento: { valor: normalized.valor, data: normalized.data, tipo_pagamento: 'desconto_proxima' }, impacto: { parcela_atual: { id: Number(state.atual.id), numero: Number(state.atual.numero), valor_total: money(state.atual.valor_total), valor_pago_anterior: money(state.atual.valor_pago || 0), valor_pago_posterior: money(atualAfter.valor_pago), excedente }, capital: { anterior: money(state.atual.valor_capital), posterior: money(atualAfter.valor_capital) }, juros: { anterior: money(Number(state.atual.valor_juros || 0) + Number(state.atual.juros_pendentes || 0) + Number(state.atual.juros_adicionais || 0)), posterior: money(Number(atualAfter.valor_juros || 0) + Number(atualAfter.juros_pendentes || 0) + Number(atualAfter.juros_adicionais || 0)) }, parcelas_futuras: futures } }; preview.ui = { title: 'Desconto da próxima parcela', fields: [['Cliente', preview.cliente.nome], ['Empréstimo', `#${preview.emprestimo.id}`], ['Valor recebido', normalized.valor], ['Data', normalized.data], ['Parcela atual', `#${state.atual.numero}`]], sections: [{ title: 'Excedente e desconto', rows: [['Excedente', excedente], ['Parcelas futuras afetadas', futures.length], ...futures.map((future) => [`Parcela #${future.numero}`, future.desconto])] }], impact: [['Capital preservado', preview.impacto.capital.posterior], ['Juros preservados', preview.impacto.juros.posterior]] }; return preview; }
async function createPaymentPreview(intent, { dbHandle = defaultDb() } = {}) { const normalized = normalizeIntent(intent); const state = await loadState(normalized, dbHandle); const updates = await aplicarDescontoProxima(state.parcelas, state.atualIndex, normalized.valor, normalized.data, ''); return { action: normalized.action, arguments: normalized, state_fingerprint: fingerprint(state, normalized), preview: buildPreview(state, normalized, updates) }; }
async function executePayment(normalized, expectedFingerprint, { dbHandle = defaultDb(), registrarEntradaPagamento = defaultRegistrarEntradaPagamento(), idempotencyKey = null } = {}) { await runAsync(dbHandle, 'BEGIN IMMEDIATE TRANSACTION'); try { const clean = normalizeIntent(normalized); const state = await loadState(clean, dbHandle); if (fingerprint(state, clean) !== expectedFingerprint) throw error('state_changed', 'Os dados mudaram desde o preview. Gere uma nova confirmacao.'); await claimActionExecution(dbHandle, { key: idempotencyKey, action: clean.action, emprestimoId: clean.emprestimo_id }); const updates = await aplicarDescontoProxima(state.parcelas, state.atualIndex, clean.valor, clean.data, ''); const preview = buildPreview(state, clean, updates); for (const update of updates) await runAsync(dbHandle, `UPDATE parcelas SET valor_pago=COALESCE(?,valor_pago),valor_excedente=COALESCE(?,valor_excedente),data_pagamento=COALESCE(?,data_pagamento),pago=COALESCE(?,pago),valor_total=COALESCE(?,valor_total),valor_capital=COALESCE(?,valor_capital),valor_juros=COALESCE(?,valor_juros),juros_pendentes=COALESCE(?,juros_pendentes),juros_adicionais=COALESCE(?,juros_adicionais),observacao=COALESCE(?,observacao),explicacao=CASE WHEN ? IS NULL THEN explicacao ELSE ? END,tipo_pagamento=COALESCE(?,tipo_pagamento) WHERE id=?`, [update.valor_pago ?? null,update.valor_excedente ?? null,update.data_pagamento ?? null,update.pago ?? null,update.valor_total ?? null,update.valor_capital ?? null,update.valor_juros ?? null,update.juros_pendentes ?? null,update.juros_adicionais ?? null,update.observacao ?? null,update.explicacao ?? null,update.explicacao ?? null,update.tipo_pagamento ?? null,update.id]); const payment = await runAsync(dbHandle, `INSERT INTO pagamentos (emprestimo_id,valor,data,tipo_pagamento,observacao,parcela_origem) VALUES (?, ?, ?, 'desconto_proxima', '', ?)`, [clean.emprestimo_id, clean.valor, clean.data, Number(state.atual.numero) - 1]); const split = splitNormalPaymentFromParcela(state.atual, clean.valor); await registrarEntradaPagamento({ emprestimo_id: clean.emprestimo_id, cliente_id: clean.cliente_id, parcela_id: state.atual.id, parcela_numero: state.atual.numero, data: clean.data, data_pagamento: clean.data, valor_total: clean.valor, valor_juros: split.juros, valor_capital: split.capital, descricao: 'Pagamento com desconto na próxima parcela registrado pela assistente', meta: { origem: 'assistente_action_gateway', pagamento_id: payment.lastID, excedente: preview.impacto.parcela_atual.excedente } }, dbHandle); await runAsync(dbHandle, 'COMMIT'); return { pagamento_id: Number(payment.lastID), preview }; } catch (err) { await runAsync(dbHandle, 'ROLLBACK').catch(() => {}); throw err; } }
module.exports = { normalizeIntent, createPaymentPreview, executePayment };
