const crypto = require('crypto');
const aplicarQuitarEmprestimo = require('../../../utils/quitar_emprestimo');
const { calcularValorQuitacao } = aplicarQuitarEmprestimo;
const { runAsync, getAsync, allAsync } = require('../../../utils/sqliteAsync');
const { claimActionExecution } = require('./actionIdempotency');
function money(value) { const n = Number(value); return Number.isFinite(n) ? Number(n.toFixed(2)) : null; }
function positiveId(value) { const n = Number(value); return Number.isInteger(n) && n > 0 ? n : null; }
function isoDate(value) { const s = String(value || '').trim(); const d = new Date(`${s}T00:00:00Z`); return /^\d{4}-\d{2}-\d{2}$/.test(s) && !Number.isNaN(d.getTime()) && d.toISOString().slice(0, 10) === s ? s : null; }
function error(code,message) { const e = new Error(message); e.code = code; return e; }
function defaultDb() { return require('../../../models/database'); } function defaultRegistrarEntradaPagamento() { return require('../../caixaService').registrarEntradaPagamento; }
function normalizeIntent(intent = {}) { if (!intent || typeof intent !== 'object' || Array.isArray(intent)) throw error('invalid_action','Intencao de acao invalida.'); const allowed=new Set(['action','cliente_id','emprestimo_id','data']); if(Object.keys(intent).some((key)=>!allowed.has(key))) throw error('invalid_action_contract','A intencao contem campos nao permitidos.'); if(String(intent.action||'')!=='quitar_emprestimo') throw error('unsupported_action','Acao nao suportada.'); const out={action:'quitar_emprestimo',cliente_id:positiveId(intent.cliente_id),emprestimo_id:positiveId(intent.emprestimo_id),data:isoDate(intent.data)}; if(!out.cliente_id||!out.emprestimo_id) throw error('entity_required','Cliente e emprestimo devem ser informados por ID exato.'); if(!out.data) throw error('invalid_date','A data deve estar no formato YYYY-MM-DD.'); return out; }
async function loadState(args, dbHandle) { const cliente=await getAsync(dbHandle,'SELECT id,nome FROM clientes WHERE id=?',[args.cliente_id]); if(!cliente) throw error('client_not_found','Cliente nao encontrado.'); const emprestimo=await getAsync(dbHandle,'SELECT id,cliente_id,modalidade,versao_atual,capital_restante FROM emprestimos WHERE id=?',[args.emprestimo_id]); if(!emprestimo) throw error('loan_not_found','Emprestimo nao encontrado.'); if(Number(emprestimo.cliente_id)!==args.cliente_id) throw error('loan_client_mismatch','O emprestimo nao pertence ao cliente informado.'); if(String(emprestimo.modalidade||'').toLowerCase()!=='parcelado') throw error('unsupported_loan_type','A acao exige emprestimo parcelado.'); const parcelas=await allAsync(dbHandle,`SELECT p.* FROM parcelas p JOIN emprestimos e ON e.id=p.emprestimo_id WHERE p.emprestimo_id=? AND (p.versao IS NULL OR p.versao=e.versao_atual) ORDER BY p.numero,p.id`,[args.emprestimo_id]); const atualIndex=parcelas.findIndex((p)=>!Number(p.pago||0)); if(atualIndex<0) throw error('loan_closed','O emprestimo ja esta quitado.'); let calculation; try { calculation=calcularValorQuitacao(parcelas,atualIndex); } catch (_) { throw error('loan_closed','O emprestimo ja esta quitado.'); } return {cliente,emprestimo,parcelas,atualIndex,calculation}; }
function fingerprint(state,args) { return crypto.createHash('sha256').update(JSON.stringify({emprestimo:[state.emprestimo.id,state.emprestimo.versao_atual,money(state.emprestimo.capital_restante)],parcelas:state.parcelas.map((p)=>[p.id,p.numero,p.valor_total,p.valor_capital,p.valor_juros,p.juros_pendentes,p.juros_adicionais,p.valor_pago,p.pago,p.versao,p.vencimento]),arguments:args,calculation:state.calculation.expected})).digest('hex'); }
function previewFor(state,args,updates) { const c=state.calculation; const preview={cliente:{id:Number(state.cliente.id),nome:String(state.cliente.nome||'')},emprestimo:{id:Number(state.emprestimo.id)},pagamento:{valor:c.expected,data:args.data,tipo_pagamento:'quitar'},quitacao:{valor_total:c.expected,capital:c.somaCapital,juros:c.jurosAtual,data:args.data},audit:{componentes:{capital:c.somaCapital,juros:c.jurosAtual,parcelas_encerradas:updates.length,parcelas_fantasma:Math.max(0,updates.length-1)}},impacto:{parcelas_encerradas:updates.length,parcela_atual:{id:Number(c.proxima.id),numero:Number(c.proxima.numero)},parcelas_fantasma:Math.max(0,updates.length-1),emprestimo_encerrado:true}}; preview.ui={title:'Quitar empréstimo',fields:[['Cliente',preview.cliente.nome],['Empréstimo',`#${preview.emprestimo.id}`],['Data',args.data],['Valor total da quitação',c.expected]],sections:[{title:'Composição',rows:[['Capital restante',c.somaCapital],['Juros da próxima parcela',c.jurosAtual],['Parcelas encerradas',updates.length],['Parcelas encerradas sem novo pagamento',preview.impacto.parcelas_fantasma]]}],impact:[['Resultado','O empréstimo será encerrado.']]}; return preview; }
async function createPaymentPreview(intent,{dbHandle=defaultDb()}={}) { const args=normalizeIntent(intent); const state=await loadState(args,dbHandle); const updates=await aplicarQuitarEmprestimo(state.parcelas,state.atualIndex,state.calculation.expected,args.data,''); return {action:args.action,arguments:args,state_fingerprint:fingerprint(state,args),preview:previewFor(state,args,updates)}; }
async function executePayment(normalized,expectedFingerprint,{dbHandle=defaultDb(),registrarEntradaPagamento=defaultRegistrarEntradaPagamento(),idempotencyKey=null}={}) { await runAsync(dbHandle,'BEGIN IMMEDIATE TRANSACTION'); try { const args=normalizeIntent(normalized); const state=await loadState(args,dbHandle); if(fingerprint(state,args)!==expectedFingerprint) throw error('state_changed','Os dados mudaram desde o preview. Gere uma nova confirmacao.'); await claimActionExecution(dbHandle,{key:idempotencyKey,action:args.action,emprestimoId:args.emprestimo_id}); const updates=await aplicarQuitarEmprestimo(state.parcelas,state.atualIndex,state.calculation.expected,args.data,''); const preview=previewFor(state,args,updates); for(const update of updates) await runAsync(dbHandle,`UPDATE parcelas SET valor_pago=COALESCE(?,valor_pago),valor_excedente=COALESCE(?,valor_excedente),data_pagamento=COALESCE(?,data_pagamento),vencimento=COALESCE(?,vencimento),pago=COALESCE(?,pago),valor_total=COALESCE(?,valor_total),valor_capital=COALESCE(?,valor_capital),valor_juros=COALESCE(?,valor_juros),observacao=COALESCE(?,observacao),explicacao=CASE WHEN ? IS NULL THEN explicacao ELSE ? END,tipo_pagamento=COALESCE(?,tipo_pagamento) WHERE id=?`,[update.valor_pago??null,update.valor_excedente??null,update.data_pagamento??null,update.vencimento??null,update.pago??null,update.valor_total??null,update.valor_capital??null,update.valor_juros??null,update.observacao??null,update.explicacao??null,update.explicacao??null,update.tipo_pagamento??null,update.id]); const payment=await runAsync(dbHandle,`INSERT INTO pagamentos (emprestimo_id,valor,data,tipo_pagamento,observacao,parcela_origem) VALUES (?, ?, ?, 'quitar', '', ?)`,[args.emprestimo_id,state.calculation.expected,args.data,Number(state.calculation.proxima.numero)-1]); await registrarEntradaPagamento({emprestimo_id:args.emprestimo_id,cliente_id:args.cliente_id,parcela_id:state.calculation.proxima.id,parcela_numero:state.calculation.proxima.numero,data:args.data,data_pagamento:args.data,valor_total:state.calculation.expected,valor_juros:state.calculation.jurosAtual,valor_capital:money(state.calculation.expected-state.calculation.jurosAtual),descricao:'Quitação de empréstimo registrada pela assistente',meta:{origem:'assistente_action_gateway',pagamento_id:payment.lastID,parcelas_encerradas:updates.length}},dbHandle); await runAsync(dbHandle,'COMMIT'); return {pagamento_id:Number(payment.lastID),preview}; } catch(err) { await runAsync(dbHandle,'ROLLBACK').catch(()=>{}); throw err; } }
module.exports={normalizeIntent,createPaymentPreview,executePayment};
